version: '2'

services:
  base:
    build: .
    image: kops:latest
  kops-eu-west-1:
    image: kops:latest
    depends_on:
      - base
    volumes:
      - ./aws:/root/.aws
      - ./ssh:/root/.ssh
      - ./kube-config/eu-west-1.conf:/root/.kube/config
    environment:
      - BUCKET=burning-candle-eu-west-1-kops-config
      - REGION=eu-west-1
      - DOMAIN=burning-candle.com
      - CLUSTER=k8s.burning-candle.com
