#!/usr/bin/env sh

if [[ -z ${AWS_PROFILE} ]]; then
    echo "AWS Profile was missing, please set the 'AWS_PROFILE' environment variable";
    exit 1
fi

if [[ ! -s ${HOME}/.aws/config ]] || [[ ! -s ${HOME}/.aws/credentials ]]; then
    echo "AWS Credentials missing, run 'aws configure' before trying to run any other command"
    exit 2
fi

if [[ ! -s ${HOME}/.ssh/id_rsa ]] || [[ ! -s ${HOME}/.ssh/id_rsa.pub ]]; then
    echo "SSH Permissions for cluster were missing, generating new ones"
    ssh-keygen -t rsa -b 4096
fi
