apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - name: hello-node
          image: christhomas/hello-node:v4
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: hello-node
spec:
  type: LoadBalancer
  selector:
    app: hello-node
  ports:
    - port: 80
      targetPort: 8080
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-node
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: hello-node.burning-candle.com
      http:
        paths:
          - backend:
              serviceName: hello-node
              servicePort: 80
